build: fix build for contrib arm boring ssl fips (#45043)
## Commit Message 
build: fix build for contrib arm boring ssl fips

## Additional Description
Building envoy on arm with boring ssl fips fails due to the following:
```
envoybuild@ip-10-92-23-225:/workspaces/envoy$ bazel cquery //contrib/exe:envoy-static --config=boringssl-fips --platforms=//bazel/platforms:linux_arm64
ERROR: /workspaces/envoy/contrib/exe/BUILD:25:16: Illegal ambiguous match on configurable attribute "deps" in //contrib/exe:envoy-static:
//bazel:linux_aarch64
//bazel:using_boringssl_fips
Multiple matches are not allowed unless one is unambiguously more specialized or they resolve to the same value. See https://bazel.build/reference/be/functions#select.
ERROR: Analysis of target '//contrib/exe:envoy-static' failed; build aborted
INFO: Elapsed time: 0.883s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

Fix is exactly the same as the aws lc one: #44661

After the change it seems to work

```
envoybuild@ip-10-92-23-225:/workspaces/envoy$ bazel cquery //contrib/exe:envoy-static --config=boringssl-fips --platforms=//bazel/platforms:linux_arm64
INFO: Analyzed target //contrib/exe:envoy-static (1463 packages loaded, 81211 targets configured).
INFO: Found 1 target...
//contrib/exe:envoy-static (39afe8a)
INFO: Elapsed time: 2.313s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

## Risk level
Low existing builds should not be affected due to the change.

Signed-off-by: aakugan <aakashganapathy2@gmail.com>